# Generated by Django 4.2.4 on 2023-10-19 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_swanimage_remove_swanclfdata_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swanclfdata',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.swanimage'),
        ),
        migrations.AlterField(
            model_name='swanimage',
            name='image',
            field=models.ImageField(max_length=200, upload_to='swan_classification/photos/'),
        ),
    ]
