# Generated by Django 4.2.4 on 2023-10-20 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_swanclfdata_image_id_alter_swanimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwanSegImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='swan_segmentation/photos/')),
            ],
        ),
        migrations.CreateModel(
            name='SwanSegMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask', models.ImageField(max_length=200, upload_to='swan_segmentation/masks/')),
            ],
        ),
        migrations.CreateModel(
            name='SwanSegResultImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_image', models.ImageField(max_length=200, upload_to='swan_segmentation/result_images/')),
            ],
        ),
        migrations.CreateModel(
            name='SwanSegData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.swansegimage')),
                ('mask_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.swansegmask')),
                ('res_image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.swansegresultimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
