# Generated by Django 4.2.4 on 2023-10-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_swansegimage_swansegmask_swansegresultimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swansegdata',
            old_name='user',
            new_name='user_id',
        ),
    ]
