# Generated by Django 4.2.4 on 2023-10-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_user_swansegdata_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swansegdata',
            old_name='user_id',
            new_name='user',
        ),
    ]
