# Generated by Django 4.2.4 on 2023-10-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_historymodel_data_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='swanclfdata',
            name='proba',
            field=models.FloatField(default=1),
        ),
    ]
